Update patch set 4
Patch Set 4:

After cherry-picking this change I'm getting
java.io.FileNotFoundException: /sys/bus/i2c/devices/1-004a/tsp: open failed: EACCES (Permission denied)
Any idea what could be causing it?

Patch-set: 4